---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: flux-system
spec:
  chart:
    spec:
      chart: datadog/datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
  interval: 30s
  releaseName: datadog
  targetNamespace: datadog
  values:
    containers:
      agent:
        resources:
          limits:
            memory: 8Mi
          requests:
            memory: 8Mi
      process-agent:
        resources:
          limits:
            memory: 4Mi
          requests:
            memory: 4Mi
    datadog:
      apiKey: ""
      apiKeyExistingSecret: datadog
      apm:
        enabled: true
      logLevel: warn
      logs:
        containerCollectAll: true
        enabled: true
      tags:
      - env: devt
    kube-state-metrics:
      resources:
        limits:
          cpu: 200m
          memory: 4Mi
        requests:
          cpu: 200m
          memory: 4Mi
    priorityClassName: high-priority
