datadog:
  apiKey: ""  # Override default so the secretfile is used
  apiKeyExistingSecret:  "datadog"
  apm:
    enabled: true
  logLevel: warn
  logs:
    enabled: true
    containerCollectAll: true
  tags:
    - env: "devt"
kube-state-metrics:
  resources:
    requests:
      cpu: 200m
      memory: 8Mi
    limits:
      cpu: 200m
      memory: 8Mi
containers:
  agent:
    resources:
      requests:
        memory: 16Mi
      limits:
        memory: 16Mi
  process-agent:
    resources:
      requests:
        memory: 8Mi
      limits:
        memory: 8Mi
priorityClassName: high-priority
